---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  generateName: disk-virt-customize-taskrun-
spec:
  taskRef:
    resolver: hub
    params:
    - name: catalog
      value: kubevirt-tekton-tasks
    - name: type
      value: artifact
    - name: kind
      value: task
    - name: name
      value: disk-virt-customize
    - name: version
      value: v0.22.0
  params:
    - name: pvc
      value: example-pvc
    - name: virtCommands
      value: |-
        install make,ansible
  podTemplate:
    securityContext:
      fsGroup: 107
      runAsUser: 107
