---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: windows11-customize-run-
spec:
  pipelineRef:
    resolver: hub
    params:
      - name: catalog
        value: kubevirt-tekton-pipelines
      - name: type
        value: artifact
      - name: kind
        value: pipeline
      - name: name
        value: windows-customize
      - name: version
        value: v0.22.0
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: windows2k22-customize-run-
spec:
  params:
    - name: sourceDiskImageName
      value: win2k22
    - name: baseDvName
      value: win2k22-customized
    - name: preferenceName
      value: windows.2k22.virtio
    - name: customizeConfigMapName
      value: windows-sqlserver
  pipelineRef:
    resolver: hub
    params:
      - name: catalog
        value: kubevirt-tekton-pipelines
      - name: type
        value: artifact
      - name: kind
        value: pipeline
      - name: name
        value: windows-customize
      - name: version
        value: v0.22.0
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: windows10-customize-run-
spec:
  params:
    - name: sourceDiskImageName
      value: win10
    - name: baseDvName
      value: win10-customized
    - name: preferenceName
      value: windows.10.virtio
  pipelineRef:
    resolver: hub
    params:
      - name: catalog
        value: kubevirt-tekton-pipelines
      - name: type
        value: artifact
      - name: kind
        value: pipeline
      - name: name
        value: windows-customize
      - name: version
        value: v0.22.0
