---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  generateName: execute-in-vm-with-ssh-taskrun-resolver-
spec:
  taskRef:
    resolver: hub
    params:
    - name: catalog
      value: kubevirt-tekton-tasks
    - name: type
      value: artifact
    - name: kind
      value: task
    - name: name
      value: execute-in-vm
    - name: version
      value: v0.21.0
  params:
    - name: vmName
      value: vm-example
    - name: secretName
      value: ssh-secret
    - name: command
      value:
        - systemctl
    - name: args
      value:
        - 'start'
        - 'postgresql.service'
