---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: windows11-installer-run-
spec:
  params:
    - name: winImageDownloadURL
      value: ${WIN_IMAGE_DOWNLOAD_URL}
    - name: acceptEula
      value: false
  pipelineRef:
    resolver: hub
    params:
      - name: catalog
        value: kubevirt-tekton-pipelines
      - name: type
        value: artifact
      - name: kind
        value: pipeline
      - name: name
        value: windows-efi-installer
      - name: version
        value: v0.22.0
  taskRunSpecs:
    - pipelineTaskName: "modify-windows-iso-file"
      podTemplate:
        securityContext:
          runAsUser: 107
          fsGroup: 107   
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: windows10-installer-run-
spec:
  params:
    - name: winImageDownloadURL
      value: ${WIN_IMAGE_DOWNLOAD_URL}
    - name: acceptEula
      value: false
    - name: preferenceName
      value: windows.10.virtio
    - name: autounattendConfigMapName
      value: windows10-efi-autounattend
    - name: baseDvName
      value: win10
    - name: isoDVName
      value: win10
  pipelineRef:
    resolver: hub
    params:
      - name: catalog
        value: kubevirt-tekton-pipelines
      - name: type
        value: artifact
      - name: kind
        value: pipeline
      - name: name
        value: windows-efi-installer
      - name: version
        value: v0.22.0
  taskRunSpecs:
    - pipelineTaskName: "modify-windows-iso-file"
      podTemplate:
        securityContext:
          runAsUser: 107
          fsGroup: 107     
  timeout: 1h0m0s
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: windows2k22-installer-run-
spec:
  params:
    - name: winImageDownloadURL
      value: ${WIN_IMAGE_DOWNLOAD_URL}
    - name: acceptEula
      value: false
    - name: preferenceName
      value: windows.2k22.virtio
    - name: autounattendConfigMapName
      value: windows2k22-autounattend
    - name: baseDvName
      value: win2k22
    - name: isoDVName
      value: win2k22
  pipelineRef:
    resolver: hub
    params:
      - name: catalog
        value: kubevirt-tekton-pipelines
      - name: type
        value: artifact
      - name: kind
        value: pipeline
      - name: name
        value: windows-efi-installer
      - name: version
        value: v0.22.0
  taskRunSpecs:
    - pipelineTaskName: "modify-windows-iso-file"
      podTemplate:
        securityContext:
          runAsUser: 107
          fsGroup: 107     
  timeout: 1h0m0s
