---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: windows10-installer-run-
  labels:
    pipelinerun: windows10-installer-run
spec:
  params:
    - name: winImageDownloadURL
      value: http://http-server/disk.img
    - name: preferenceName
      value: windows.10.virtio
    - name: autounattendConfigMapName
      value: windows10-efi-autounattend
    - name: baseDvName
      value: win10
    - name: isoDVName
      value: win10
    - name: acceptEula
      value: "true"
  pipelineRef:
    name: windows-efi-installer
