---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: windows11-installer-run-
  labels:
    pipelinerun: windows11-installer-run
spec:
  params:
    - name: winImageDownloadURL
      value: http://http-server/disk.img
    - name: baseDvNamespace
      value: kubevirt
    - name: acceptEula
      value: "true"
  pipelineRef:
    name: windows-efi-installer
