---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  generateName: {{ item.name }}-
spec:
  taskRef:
    resolver: hub
    params:
    - name: catalog
      value: kubevirt-tekton-tasks
    - name: type
      value: artifact
    - name: kind
      value: task
    - name: name
      value: {{ task_name }}
    - name: version
      value: {{ catalog_version }}
  params:
    - name: pvc
      value: example-pvc
    - name: virtCommands
      value: |-
        install make,ansible
  podTemplate:
    securityContext:
      fsGroup: 107
      runAsUser: 107
