apiVersion: v1
kind: Secret
metadata:
  name: {{ item.name }}
type: Opaque
stringData:
  password: mysecretpassword
---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  generateName: {{ item.name }}-
spec:
  taskRef:
    kind: Task
    name: {{ task_name }}
  params:
    - name: pvc
      value: example-pvc
    - name: customizeCommands
      value: |-
        update
        install make,ansible
        delete /var/cache/dnf
        root-password file:/data/password
  workspaces:
    - name: data
      secret:
        name: {{ item.name }}
  podTemplate:
    securityContext:
      fsGroup: 107
      runAsUser: 107
