---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  annotations:
    tekton.dev/pipelines.minVersion: "0.43.0"
    tekton.dev/categories: Automation
    tekton.dev/tags: kubevirt
    tekton.dev/displayName: "KubeVirt Windows Customize"
    tekton.dev/platforms: "linux/amd64"
    artifacthub.io/maintainers: |
      - name: KubeVirt Tekton tasks maintainers
        email: kubevirt-tekton-tasks@redhat.com
    artifacthub.io/provider: KubeVirt
    artifacthub.io/recommendations: |
      - url: https://kubevirt.io/
    artifacthub.io/category: integration-delivery
  labels:
    app.kubernetes.io/version: v0.22.0
  name: windows-customize
spec:
  description: >-
    windows-customize pipeline provides functionality for windows VMs to e.g.
    install sql server, or install VS Code into windows VM. This pipeline can be 
    reused for customizing Windows 10, 11 or server 2k22. Different OS versions 
    requires different customizeConfigMapName parameter with unattend.xml.
  params:
    - name: unattendXMLConfigMapsURL
      description: Allows to specify a download URL to a file with ConfigMaps containing a Windows `unattend.xml` file. These ConfigMaps can be used for automated customization of Windows. Specify the desired ConfigMap name in `customizeConfigMapName` parameter.
      type: string
      default: https://raw.githubusercontent.com/kubevirt/kubevirt-tekton-tasks/main/release/pipelines/windows-customize/configmaps/windows-customize-configmaps.yaml
    - name: instanceTypeName
      type: string
      description: Name of VirtualMachineClusterInstancetype object
      default: u1.large
    - name: instanceTypeKind
      type: string
      description: Kind of VirtualMachineInstancetype object
      default: VirtualMachineClusterInstancetype
    - name: preferenceName
      type: string
      description: Name of VirtualMachineClusterPreference object
      default: windows.11.virtio
    - name: virtualMachinePreferenceKind
      type: string
      description: Kind of virtualMachinePreference object
      default: VirtualMachineClusterPreference
    - name: customizeConfigMapName
      description: Name of the ConfigMap containing the customization and sysprep configuration files (unattend.xml, etc.). For example windows10-sqlserver or windows11-vs-code. It is possible to provide customize ConfigMaps created by the user too.
      type: string
      default: windows-vs-code
    - name: sourceDiskImageName
      description: Name of the windows source disk which will be copied and modified with sysprep
      type: string
      default: win11
    - name: baseDvName
      description: Name of the result windows disk
      type: string
      default: win11-customized
  tasks:
    - name: import-unattend-configmaps
      params:
        - name: SCRIPT
          value: oc apply -f $(params.unattendXMLConfigMapsURL)
        - name: VERSION
          value: latest
      taskRef:
        resolver: hub
        params:
          - name: catalog
            value: tekton-catalog-tasks
          - name: type
            value: artifact
          - name: kind
            value: task
          - name: name
            value: openshift-client
          - name: version
            value: 0.2.0
    - name: copy-vm-root-disk
      runAfter:
        - import-unattend-configmaps
      taskRef:
        resolver: hub
        params:
          - name: catalog
            value: kubevirt-tekton-tasks
          - name: type
            value: artifact
          - name: kind
            value: task
          - name: name
            value: modify-data-object
          - name: version
            value: v0.22.0
      params:
        - name: manifest
          value: |-
            apiVersion: cdi.kubevirt.io/v1beta1
            kind: DataVolume
            metadata:
              name: $(params.baseDvName)
            spec:
              storage: {}
              source: 
                pvc:
                  name: $(params.sourceDiskImageName)
                  namespace: $(context.pipelineRun.namespace)
        - name: waitForSuccess
          value: false
        - name: allowReplace
          value: true
    - name: create-vm
      params:
        - name: runStrategy
          value: RerunOnFailure
        - name: setOwnerReference
          value: true
        - name: manifest
          value: |-          
            apiVersion: kubevirt.io/v1
            kind: VirtualMachine
            metadata:
              generateName: windows-customize-
            spec:
              instancetype:
                kind: $(params.instanceTypeKind)
                name: $(params.instanceTypeName)
              preference:
                kind: $(params.virtualMachinePreferenceKind)
                name: $(params.preferenceName)
              template:
                spec:
                  evictionStrategy: LiveMigrateIfPossible
                  domain:
                    devices:
                      disks:
                        - disk:
                            bus: virtio
                          name: rootdisk
                          bootOrder: 1
                        - cdrom:
                            bus: sata
                          name: sysprep
                  volumes:
                  - name: sysprep
                    sysprep:
                      configMap: 
                        name: $(params.customizeConfigMapName)
                  - dataVolume:
                      name:  $(tasks.copy-vm-root-disk.results.name)
                    name: rootdisk
      taskRef:
        resolver: hub
        params:
          - name: catalog
            value: kubevirt-tekton-tasks
          - name: type
            value: artifact
          - name: kind
            value: task
          - name: name
            value: create-vm-from-manifest
          - name: version
            value: v0.22.0
      runAfter:
        - copy-vm-root-disk
    - name: wait-for-vmi-status
      params:
        - name: vmiName
          value: $(tasks.create-vm.results.name)
        - name: vmiNamespace
          value: $(tasks.create-vm.results.namespace)
        - name: successCondition
          value: status.phase == Succeeded
        - name: failureCondition
          value: status.phase in (Failed, Unknown)
      runAfter:
        - create-vm
      timeout: 2h
      taskRef:
        resolver: hub
        params:
          - name: catalog
            value: kubevirt-tekton-tasks
          - name: type
            value: artifact
          - name: kind
            value: task
          - name: name
            value: wait-for-vmi-status
          - name: version
            value: v0.22.0
    - name: create-datasource-root-disk
      runAfter:
        - wait-for-vmi-status
      taskRef:
        resolver: hub
        params:
          - name: catalog
            value: kubevirt-tekton-tasks
          - name: type
            value: artifact
          - name: kind
            value: task
          - name: name
            value: modify-data-object
          - name: version
            value: v0.22.0
      params:
        - name: manifest
          value: |-
            apiVersion: cdi.kubevirt.io/v1beta1
            kind: DataSource
            metadata:
              labels:
                "instancetype.kubevirt.io/default-instancetype-kind": $(params.instanceTypeKind)
                "instancetype.kubevirt.io/default-instancetype": $(params.instanceTypeName)
                "instancetype.kubevirt.io/default-preference-kind": $(params.virtualMachinePreferenceKind)
                "instancetype.kubevirt.io/default-preference": $(params.preferenceName)
              name: $(tasks.copy-vm-root-disk.results.name)
              namespace: $(tasks.copy-vm-root-disk.results.namespace)
            spec:
              source:
                pvc:
                  name: $(tasks.copy-vm-root-disk.results.name)
                  namespace: $(tasks.copy-vm-root-disk.results.namespace)
        - name: waitForSuccess
          value: false
        - name: allowReplace
          value: true
  finally:
    - name: cleanup-vm
      params:
        - name: vmName
          value: $(tasks.create-vm.results.name)
        - name: vmNamespace
          value: $(tasks.create-vm.results.namespace)
        - name: delete
          value: true
      timeout: 10m
      taskRef:
        resolver: hub
        params:
          - name: catalog
            value: kubevirt-tekton-tasks
          - name: type
            value: artifact
          - name: kind
            value: task
          - name: name
            value: cleanup-vm
          - name: version
            value: v0.22.0
    - name: delete-imported-configmaps
      params:
        - name: SCRIPT
          value: oc delete -f $(params.unattendXMLConfigMapsURL)
        - name: VERSION
          value: latest
      taskRef:
        resolver: hub
        params:
          - name: catalog
            value: tekton-catalog-tasks
          - name: type
            value: artifact
          - name: kind
            value: task
          - name: name
            value: openshift-client
          - name: version
            value: 0.2.0
  results:
    - name: baseDvName
      description: Name of the created base DataVolume
      value: $(tasks.copy-vm-root-disk.results.name)
    - name: baseDvNamespace
      description: Namespace of the created base DataVolume
      value: $(tasks.copy-vm-root-disk.results.namespace)
