---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: virt-sysprep-updater
spec:
  tasks:
    - name: modify-data-object
      params:
        - name: manifest
          value: |
            apiVersion: cdi.kubevirt.io/v1beta1
            kind: DataVolume
            metadata:
              generateName: virt-sysprep-updated-vm-base-
            spec:
              pvc:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 5Gi
                volumeMode: Filesystem
              source:
                http:
                  url: https://download.fedoraproject.org/pub/fedora/linux/releases/33/Cloud/x86_64/images/Fedora-Cloud-Base-33-1.2.x86_64.raw.xz
        - name: waitForSuccess
          value: 'true'
      taskRef:
        kind: Task
        name: modify-data-object
    - name: disk-virt-sysprep
      params:
        - name: pvc
          value: "$(tasks.modify-data-object.results.name)"
        - name: virtCommands
          value: |
            run-command yum update -y
        - name: additionalVirtOptions
          value: "--network"
      taskRef:
        kind: Task
        name: disk-virt-sysprep
      runAfter:
        - modify-data-object
    - name: create-vm-from-manifest
      params:
        - name: manifest
          value: |
            apiVersion: kubevirt.io/v1
            kind: VirtualMachine
            metadata:
              generateName: virt-sysprep-updated-vm-
              annotation:
                description: Fedora VM generated by server-deployer pipeline
              labels:
                app: virt-sysprep-updated-vm
            spec:
              running: false
              template:
                metadata:
                  labels:
                    kubevirt.io/domain: virt-sysprep-updated-vm
                spec:
                  domain:
                    cpu:
                      cores: 2
                      sockets: 1
                      threads: 1
                    devices:
                      disks:
                        - name: rootdisk
                          bootOrder: 1
                          disk:
                            bus: virtio
                        - name: cloudinitdrive
                          disk:
                            bus: virtio
                      interfaces:
                        - bridge: {}
                          name: default
                      networkInterfaceMultiqueue: true
                      rng: {}
                    resources:
                      requests:
                        memory: 2Gi
                  hostname: virt-sysprep-updated-vm
                  networks:
                    - name: default
                      pod: {}
                  volumes:
                    - name: rootdisk
                    - name: cloudinitdrive
                      cloudInitConfigDrive:
                        userData: |
                          #cloud-config
                          password: fedora
                          chpasswd: { expire: False }
        - name: ownDataVolumes
          value:
            - "rootdisk:$(tasks.modify-data-object.results.name)"
      runAfter:
        - disk-virt-sysprep
      taskRef:
        kind: Task
        name: create-vm-from-manifest
