---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  generateName: wait-for-vmi-status-taskrun-resolver-
spec:
  taskRef:
    resolver: hub
    params:
    - name: catalog
      value: kubevirt-tekton-tasks
    - name: type
      value: artifact
    - name: kind
      value: task
    - name: name
      value: wait-for-vmi-status
    - name: version
      value: v0.22.0
  params:
    - name: vmiName
      value: example-vm
    - name: successCondition
      value: "status.phase == Succeeded"
    - name: failureCondition
      value: "status.phase in (Failed, Unknown)"
