---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  generateName: create-vm-from-template-taskrun-resolver-
spec:
  taskRef:
    resolver: hub
    params:
    - name: catalog
      value: kubevirt-tekton-tasks
    - name: type
      value: artifact
    - name: kind
      value: task
    - name: name
      value: create-vm-from-template
    - name: version
      value: v0.21.0
  params:
  - name: templateName
    value: vm-template-example
  - name: templateParams
    value:
      - 'NAME:example-vm'
  - name: ownDataVolumes
    value:
      - example-dv
