repo_dir: ../..
output_dir: ./dist
manifests_output_dir: "{{ output_dir }}/manifests"
readme_output_dir: "{{ output_dir }}/readme"
readme_output_dir_tmp: "{{ readme_output_dir }}/tmp"
examples_output_dir: "{{ output_dir }}/examples"
examples_taskruns_output_dir: "{{ examples_output_dir }}/taskruns"
manifest_templates_dir: ./manifests
examples_templates_dir: ./examples
readmes_templates_dir: ./readmes
role_name: "{{ task_name }}-task"
sa_name: "{{ role_name }}"
role_binding_name: "{{ role_name }}"
default_file_mode: "0644"
version: "{{ lookup('env','RELEASE_VERSION')| default('latest', true) }}"
remove_catalog_version_prefix: "{{ lookup('env','REMOVE_CATALOG_VERSION_PREFIX')| default(false) | bool}}"
catalog_version: "{{ version[1:] if remove_catalog_version_prefix else version }}"

windows10: windows10
windows11: windows11
windows2k22: windows2k22
pipelines_output_dir: ../release/pipelines
efi_pipeline_name: windows-efi-installer
customize_pipeline_name: windows-customize
efi_pipeline_dir: "{{pipelines_output_dir}}/{{ efi_pipeline_name }}"
customize_pipeline_dir: "{{pipelines_output_dir}}/{{ customize_pipeline_name }}"
