---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  generateName: create-vm-from-manifest-taskrun-resolver-
spec:
  taskRef:
    resolver: hub
    params:
    - name: catalog
      value: kubevirt-tekton-tasks
    - name: type
      value: artifact
    - name: kind
      value: task
    - name: name
      value: create-vm-from-manifest
    - name: version
      value: v0.21.0
  params:
  - name: manifest
    value: |
      <VM manifest>
